export interface BrandingStatistic {
  id: string;
  percentage: number;
  statement: string;
  source: string;
  categories: string[];
}

export const brandingStatistics: BrandingStatistic[] = [
  {
    id: 'social-media-facebook',
    percentage: 79,
    statement: 'of marketers say Facebook is the top social media platform for experiential marketing',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'community-building']
  },
  {
    id: 'video-purchase',
    percentage: 64,
    statement: 'of consumers purchase after watching a brand video',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'visual-identity']
  },
  {
    id: 'brand-name-decisions',
    percentage: 77,
    statement: 'of consumers make purchase decisions based on brand name',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: 'marketing-engagement',
    percentage: 36,
    statement: 'of consumers are extremely likely to engage with brands through marketing messages',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'digital-experience', 'community-building']
  },
  {
    id: 'influencer-campaigns',
    percentage: 34,
    statement: 'of brands are running influencer marketing campaigns to increase awareness',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'content-strategy', 'community-building']
  },
  {
    id: 'blog-leads',
    percentage: 67,
    statement: 'more leads are generated by companies through blogs',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'digital-experience']
  },
  {
    id: 'familiar-brands',
    percentage: 63,
    statement: 'of customers are more willing to buy from familiar brands',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'brand-architecture', 'visual-identity']
  },
  {
    id: 'social-media-recognition',
    percentage: 76,
    statement: 'of small businesses use social media to increase brand recognition',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'brand-strategy', 'community-building']
  },
  {
    id: 'social-media-purchase',
    percentage: 77,
    statement: 'of consumers purchase or prefer purchasing from brands they follow on social media',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'community-building', 'brand-strategy']
  },
  {
    id: 'genz-discovery',
    percentage: 38,
    statement: 'of Gen Z prefer to discover brands through social media',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'brand-strategy', 'community-building']
  },
  {
    id: 'social-media-following',
    percentage: 90,
    statement: 'of social media users follow at least one brand on social media',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'community-building']
  },
  {
    id: 'brand-recognition-purchase',
    percentage: 50,
    statement: 'of consumers are more likely to buy from brands they recognize',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: 'virtual-events',
    percentage: 31,
    statement: 'of marketers chose to conduct virtual events in 2022 to increase recognition',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'community-building', 'brand-strategy']
  },
  {
    id: 'logo-recognition',
    percentage: 75,
    statement: 'of people recognize a brand by its logo',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'signature-color',
    percentage: 80,
    statement: 'increase in brand recognition when using a signature color',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'trust-requirement',
    percentage: 81,
    statement: 'of consumers need to trust a brand to consider buying from it',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'trust-premium',
    percentage: 46,
    statement: 'of consumers in 2023 were ready to pay more for a brand they trust',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: 'trust-loyalty',
    percentage: 88,
    statement: 'of consumers trust and become loyal to a brand after three or more purchases',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'user-generated-content',
    percentage: 80,
    statement: 'of online shoppers would consider buying from a website with user-generated content and testimonials',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'community-building']
  },
  {
    id: 'brand-guidelines',
    percentage: 85,
    statement: 'of organizations reported that they had brand guidelines',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: 'consistent-presentation-growth',
    percentage: 35,
    statement: 'of organizations saw 10-20% growth in revenue due to consistent brand presentation',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: 'consistent-branding-revenue',
    percentage: 60,
    statement: 'of companies reported that consistent branding added 10-20% to their revenue growth',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: 'consistent-messaging',
    percentage: 32,
    statement: 'of brands stated that consistent messaging increased brand revenue by 20%',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'content-strategy', 'brand-architecture']
  },
  {
    id: 'personal-brand-resume',
    percentage: 70,
    statement: 'of employers say personal brand is more important than a resume',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: 'employee-brand-influence',
    percentage: 84,
    statement: 'of consumers believe a company\'s brand is influenced by employee personal brands',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'ceo-reputation',
    percentage: 50,
    statement: 'of a company\'s reputation can be influenced by its CEO',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'website-design-recommendation',
    percentage: 57,
    statement: 'of users won\'t recommend a brand without good website design',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'visual-identity']
  },
  {
    id: 'non-descriptive-logos',
    percentage: 60,
    statement: 'of companies use non-descriptive logos, 40% use descriptive ones',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'fortune-500-logos',
    percentage: 60,
    statement: 'of Fortune 500 companies use combination logos',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'website-design-importance',
    percentage: 88,
    statement: 'of consumers consider design important when surfing a brand website',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'visual-identity']
  },
  {
    id: 'branding-budget',
    percentage: 15,
    statement: 'of marketing budgets are spent on branding and rebranding by most companies (10-20% range)',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: 'personalized-marketing',
    percentage: 94,
    statement: 'of brand marketers accept the positive influence of personalized marketing on sales',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'brand-strategy']
  },
  {
    id: 'influencer-spending',
    percentage: 22,
    statement: 'of brands spent $10K-$50K on influencer marketing in 2023',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'community-building', 'brand-strategy']
  },
  {
    id: 'email-marketing',
    percentage: 64,
    statement: 'of small businesses use email marketing',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: 'b2b-brand-growth',
    percentage: 77,
    statement: 'of B2B marketers try to build a strong brand for company growth',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: 'b2b-branded-content',
    percentage: 75,
    statement: 'of B2B buyers want branded content for research',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'brand-strategy']
  },
  {
    id: 'b2b-personal-values',
    percentage: 200,
    statement: 'more likely for B2B consumers to buy from brands showing personal values vs. business values',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'b2b-brand-awareness',
    percentage: 84,
    statement: 'of B2B marketers state their main goal is brand awareness',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: 'b2c-purpose-driven',
    percentage: 500,
    statement: 'more likely for B2C consumers to buy from brands with solid purpose (4-6x)',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'loyalty-programs',
    percentage: 83,
    statement: 'of shoppers say loyalty programs influence decisions to buy again from a brand',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'digital-experience']
  },
  {
    id: 'bad-reputation-rejection',
    percentage: 69,
    statement: 'of job candidates reject offers from brands with bad reputation',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'employer-branding-advantage',
    percentage: 89,
    statement: 'of HR leaders say strong employer branding gives competitive advantage in attracting talent',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'reputation-before-applying',
    percentage: 82,
    statement: 'of potential candidates considered brand reputation before applying for jobs in 2023',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'colors-brand-visibility',
    percentage: 85,
    statement: 'of buyers say colors increase brand visibility and buying decisions',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'sound-jingle-value',
    percentage: 5,
    statement: 'increase in perceived value for brands with recognizable sound/jingle',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'smell-brand-memory',
    percentage: 84,
    statement: 'of consumers remember a brand if it has a particular smell',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: 'authenticity-importance',
    percentage: 88,
    statement: 'of customers place importance on authenticity in branding efforts',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  // Additional Edelman Trust Barometer 2025 stats
  {
    id: 'trust-brands-over-institutions',
    percentage: 80,
    statement: 'of people trust brands they use more than business, media, government, NGOs, and employers',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: 'cultural-authenticity',
    percentage: 73,
    statement: 'say their trust in a brand would increase if it authentically reflected today\'s culture',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building', 'content-strategy']
  },
  {
    id: 'ai-platform-usage',
    percentage: 55,
    statement: 'of consumers use generative AI platforms',
    source: 'Edelman Trust Barometer 2025',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: 'ai-shopping-usage',
    percentage: 91,
    statement: 'of AI platform users use them for shopping-related activities',
    source: 'Edelman Trust Barometer 2025',
    categories: ['digital-experience', 'brand-strategy']
  },
  {
    id: 'domestic-brand-trust',
    percentage: 15,
    statement: 'average trust gap favoring domestically headquartered brands over foreign counterparts',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  }
];

// Helper functions to filter statistics by categories
export const getStatisticsByCategory = (category: string): BrandingStatistic[] => {
  return brandingStatistics.filter(stat => stat.categories.includes(category));
};

export const getStatisticsByCategories = (categories: string[]): BrandingStatistic[] => {
  return brandingStatistics.filter(stat => 
    categories.some(category => stat.categories.includes(category))
  );
};

export const getRandomStatistics = (count: number): BrandingStatistic[] => {
  const shuffled = [...brandingStatistics].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

export const getStatisticById = (id: string): BrandingStatistic | undefined => {
  return brandingStatistics.find(stat => stat.id === id);
};