import { STATISTIC_IDS } from './statisticIds';

export interface BrandingStatistic {
  id: string;
  percentage: number;
  statement: string;
  source: string;
  categories: string[];
}

export const brandingStatistics: BrandingStatistic[] = [
  {
    id: STATISTIC_IDS.SOCIAL_MEDIA_FACEBOOK,
    percentage: 79,
    statement: 'of marketers say Facebook is the top social media platform for experiential marketing',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.VIDEO_PURCHASE,
    percentage: 64,
    statement: 'of consumers purchase after watching a brand video',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.BRAND_NAME_DECISIONS,
    percentage: 77,
    statement: 'of consumers make purchase decisions based on brand name',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.MARKETING_ENGAGEMENT,
    percentage: 36,
    statement: 'of consumers are extremely likely to engage with brands through marketing messages',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'digital-experience', 'community-building']
  },
  {
    id: STATISTIC_IDS.INFLUENCER_CAMPAIGNS,
    percentage: 34,
    statement: 'of brands are running influencer marketing campaigns to increase awareness',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'content-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.BLOG_LEADS,
    percentage: 67,
    statement: 'more leads are generated by companies through blogs',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'digital-experience']
  },
  {
    id: STATISTIC_IDS.FAMILIAR_BRANDS,
    percentage: 63,
    statement: 'of customers are more willing to buy from familiar brands',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'brand-architecture', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.SOCIAL_MEDIA_RECOGNITION,
    percentage: 76,
    statement: 'of small businesses use social media to increase brand recognition',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.SOCIAL_MEDIA_PURCHASE,
    percentage: 77,
    statement: 'of consumers purchase or prefer purchasing from brands they follow on social media',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'community-building', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.GENZ_DISCOVERY,
    percentage: 38,
    statement: 'of Gen Z prefer to discover brands through social media',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.SOCIAL_MEDIA_FOLLOWING,
    percentage: 90,
    statement: 'of social media users follow at least one brand on social media',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'community-building']
  },
  {
    id: STATISTIC_IDS.BRAND_RECOGNITION_PURCHASE,
    percentage: 50,
    statement: 'of consumers are more likely to buy from brands they recognize',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.VIRTUAL_EVENTS,
    percentage: 31,
    statement: 'of marketers chose to conduct virtual events in 2022 to increase recognition',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'community-building', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.LOGO_RECOGNITION,
    percentage: 75,
    statement: 'of people recognize a brand by its logo',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.SIGNATURE_COLOR,
    percentage: 80,
    statement: 'increase in brand recognition when using a signature color',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.TRUST_REQUIREMENT,
    percentage: 81,
    statement: 'of consumers need to trust a brand to consider buying from it',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.TRUST_PREMIUM,
    percentage: 46,
    statement: 'of consumers in 2023 were ready to pay more for a brand they trust',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.TRUST_LOYALTY,
    percentage: 88,
    statement: 'of consumers trust and become loyal to a brand after three or more purchases',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.USER_GENERATED_CONTENT,
    percentage: 80,
    statement: 'of online shoppers would consider buying from a website with user-generated content and testimonials',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.BRAND_GUIDELINES,
    percentage: 85,
    statement: 'of organizations reported that they had brand guidelines',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.CONSISTENT_PRESENTATION_GROWTH,
    percentage: 35,
    statement: 'of organizations saw 10-20% growth in revenue due to consistent brand presentation',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.CONSISTENT_BRANDING_REVENUE,
    percentage: 60,
    statement: 'of companies reported that consistent branding added 10-20% to their revenue growth',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.CONSISTENT_MESSAGING,
    percentage: 32,
    statement: 'of brands stated that consistent messaging increased brand revenue by 20%',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'content-strategy', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.PERSONAL_BRAND_RESUME,
    percentage: 70,
    statement: 'of employers say personal brand is more important than a resume',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.EMPLOYEE_BRAND_INFLUENCE,
    percentage: 84,
    statement: 'of consumers believe a company\'s brand is influenced by employee personal brands',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.CEO_REPUTATION,
    percentage: 50,
    statement: 'of a company\'s reputation can be influenced by its CEO',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.WEBSITE_DESIGN_RECOMMENDATION,
    percentage: 57,
    statement: 'of users won\'t recommend a brand without good website design',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.NON_DESCRIPTIVE_LOGOS,
    percentage: 60,
    statement: 'of companies use non-descriptive logos, 40% use descriptive ones',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.FORTUNE_500_LOGOS,
    percentage: 60,
    statement: 'of Fortune 500 companies use combination logos',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.WEBSITE_DESIGN_IMPORTANCE,
    percentage: 88,
    statement: 'of consumers consider design important when surfing a brand website',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.BRANDING_BUDGET,
    percentage: 15,
    statement: 'of marketing budgets are spent on branding and rebranding by most companies (10-20% range)',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.PERSONALIZED_MARKETING,
    percentage: 94,
    statement: 'of brand marketers accept the positive influence of personalized marketing on sales',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.INFLUENCER_SPENDING,
    percentage: 22,
    statement: 'of brands spent $10K-$50K on influencer marketing in 2023',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'community-building', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.EMAIL_MARKETING,
    percentage: 64,
    statement: 'of small businesses use email marketing',
    source: 'WiserNotify 2025',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.B2B_BRAND_GROWTH,
    percentage: 77,
    statement: 'of B2B marketers try to build a strong brand for company growth',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.B2B_BRANDED_CONTENT,
    percentage: 75,
    statement: 'of B2B buyers want branded content for research',
    source: 'WiserNotify 2025',
    categories: ['content-strategy', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.B2B_PERSONAL_VALUES,
    percentage: 200,
    statement: 'more likely for B2B consumers to buy from brands showing personal values vs. business values',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.B2B_BRAND_AWARENESS,
    percentage: 84,
    statement: 'of B2B marketers state their main goal is brand awareness',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.B2C_PURPOSE_DRIVEN,
    percentage: 500,
    statement: 'more likely for B2C consumers to buy from brands with solid purpose (4-6x)',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.LOYALTY_PROGRAMS,
    percentage: 83,
    statement: 'of shoppers say loyalty programs influence decisions to buy again from a brand',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'digital-experience']
  },
  {
    id: STATISTIC_IDS.BAD_REPUTATION_REJECTION,
    percentage: 69,
    statement: 'of job candidates reject offers from brands with bad reputation',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.EMPLOYER_BRANDING_ADVANTAGE,
    percentage: 89,
    statement: 'of HR leaders say strong employer branding gives competitive advantage in attracting talent',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.REPUTATION_BEFORE_APPLYING,
    percentage: 82,
    statement: 'of potential candidates considered brand reputation before applying for jobs in 2023',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.COLORS_BRAND_VISIBILITY,
    percentage: 85,
    statement: 'of buyers say colors increase brand visibility and buying decisions',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.SOUND_JINGLE_VALUE,
    percentage: 5,
    statement: 'increase in perceived value for brands with recognizable sound/jingle',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.SMELL_BRAND_MEMORY,
    percentage: 84,
    statement: 'of consumers remember a brand if it has a particular smell',
    source: 'WiserNotify 2025',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.AUTHENTICITY_IMPORTANCE,
    percentage: 88,
    statement: 'of customers place importance on authenticity in branding efforts',
    source: 'WiserNotify 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.TRUST_BRANDS_OVER_INSTITUTIONS,
    percentage: 80,
    statement: 'of people trust brands they use more than business, media, government, NGOs, and employers',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.CULTURAL_AUTHENTICITY,
    percentage: 73,
    statement: 'say their trust in a brand would increase if it authentically reflected today\'s culture',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.AI_PLATFORM_USAGE,
    percentage: 55,
    statement: 'of consumers use generative AI platforms',
    source: 'Edelman Trust Barometer 2025',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.AI_SHOPPING_USAGE,
    percentage: 91,
    statement: 'of AI platform users use them for shopping-related activities',
    source: 'Edelman Trust Barometer 2025',
    categories: ['digital-experience', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.DOMESTIC_BRAND_TRUST,
    percentage: 15,
    statement: 'average trust gap favoring domestically headquartered brands over foreign counterparts',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building', 'brand-architecture']
  },
    {
    id: STATISTIC_IDS.FACEBOOK_PRIMARY_PLATFORM_USAGE,
    percentage: 86,
    statement: 'of marketers worldwide use Facebook as their primary platform',
    source: 'Sprout Social Index 2024',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.FACEBOOK_ROI_DRIVER,
    percentage: 40,
    statement: 'of marketers cite Facebook as one of their top three drivers of ROI',
    source: 'Sprout Social Index 2024',
    categories: ['digital-experience', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.EXPERIENTIAL_MARKETING_INVESTMENT_GROWTH,
    percentage: 47,
    statement: 'of marketers increased investments in experiential marketing in 2023',
    source: 'Event Marketing Institute',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.VIDEO_PURCHASE_LIKELIHOOD_INCREASE,
    percentage: 64,
    statement: 'of consumers are more likely to purchase a product after watching a video about it',
    source: 'Wyzowl Video Marketing Statistics',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.VIDEO_PURCHASE_CONVICTION,
    percentage: 84,
    statement: 'of people say they have been convinced to buy a product by watching a brand video',
    source: 'Wyzowl Video Marketing Statistics',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.VIDEO_ONLINE_CONFIDENCE_BOOST,
    percentage: 52,
    statement: 'of consumers say watching a video makes them more confident in buying online',
    source: 'Animoto Video Marketing Study',
    categories: ['digital-experience', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.BRAND_RECOGNITION_IMPORTANCE,
    percentage: 71,
    statement: 'of consumers said it was important that they recognize a brand before making a purchase',
    source: 'OnBuy Brand Recognition Study',
    categories: ['brand-strategy', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.FAMILIAR_BRAND_PREFERENCE,
    percentage: 63,
    statement: 'of customers are more willing to buy from familiar brands',
    source: 'Nielsen Consumer Trust Survey',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.BRAND_NAME_PURCHASE_FACTOR,
    percentage: 52,
    statement: 'of respondents selected recognizing a brand name as the most important purchase factor',
    source: 'OnBuy Brand Recognition Study',
    categories: ['brand-strategy', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.CONSUMER_BRAND_TRUST_GAP,
    percentage: 34,
    statement: 'of consumers trust most of the brands they buy',
    source: 'Edelman Trust Barometer 2019',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.TRUST_AS_DECIDING_FACTOR,
    percentage: 81,
    statement: 'say trust is a deciding factor or deal-breaker in purchasing decisions',
    source: 'Edelman Trust Barometer 2019',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.TRUST_RANKING_AMONG_FACTORS,
    percentage: 85,
    statement: 'rank quality as top factor, with trust (81%), convenience (84%), and value (84%) following',
    source: 'Edelman Trust Barometer 2019',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.COLOR_BRAND_RECOGNITION_INCREASE,
    percentage: 80,
    statement: 'increase in brand recognition when using consistent color schemes',
    source: 'University of Loyola Color Psychology Study',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.COLOR_READING_COMPREHENSION_IMPROVEMENT,
    percentage: 40,
    statement: 'improvement in reading comprehension when using appropriate colors',
    source: 'University of Loyola Color Psychology Study',
    categories: ['visual-identity', 'digital-experience']
  },
  {
    id: STATISTIC_IDS.SIGNATURE_COLOR_RECALL_ASSOCIATION,
    percentage: 67,
    statement: 'of consumers associate signature colors with brand recall',
    source: 'Color Marketing Group Study',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.BRAND_CONSISTENCY_REVENUE_IMPACT,
    percentage: 68,
    statement: 'of businesses say brand consistency has contributed to revenue growth of 10% or more',
    source: 'Lucidpress Brand Consistency Report',
    categories: ['brand-strategy', 'visual-identity', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.BRAND_CONSISTENCY_REVENUE_BOOST,
    percentage: 33,
    statement: 'of businesses report that brand consistency helps boost revenue by 20% or more',
    source: 'Lucidpress Brand Consistency Report',
    categories: ['brand-strategy', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.BRAND_CONSISTENCY_VISIBILITY_INCREASE,
    percentage: 23,
    statement: 'increase in revenue from consistent brand presentation across all platforms',
    source: 'Lucidpress Brand Consistency Report',
    categories: ['brand-strategy', 'visual-identity']
  },
  {
    id: STATISTIC_IDS.CONSUMERS_EXPECT_BRAND_SOCIAL_STANCE,
    percentage: 64,
    statement: 'of consumers expect brands to take a stand on social issues',
    source: 'Sprout Social Consumer Index',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.SUSTAINABLE_PRODUCT_PREMIUM_WILLINGNESS,
    percentage: 73,
    statement: 'of consumers are willing to pay more for sustainable products',
    source: 'Nielsen Sustainability Report',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.PURPOSE_DRIVEN_BRAND_GROWTH_ADVANTAGE,
    percentage: 200,
    statement: 'faster growth rate for purpose-driven brands compared to traditional brands',
    source: 'Kantar Purpose 2020 Study',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.DOMESTIC_PREFERENCE_CULTURAL_VARIATION,
    percentage: 25,
    statement: 'variation in domestic brand preference across different countries and cultures',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.ECONOMIC_UNCERTAINTY_TRUST_GAPS,
    percentage: 35,
    statement: 'increase in trust gaps during periods of economic uncertainty',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.LOCAL_BRAND_TRUST_ADVANTAGES,
    percentage: 18,
    statement: 'average trust advantage for local brands over global brands in their home markets',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'brand-architecture']
  },
  {
    id: STATISTIC_IDS.BRAND_TRUST_VS_INSTITUTIONAL_TRUST,
    percentage: 45,
    statement: 'higher trust rating for familiar brands compared to government institutions',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.CONSUMER_TRUST_SHIFT_TRENDS,
    percentage: 60,
    statement: 'of consumers report trusting brands more than they did 5 years ago',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'community-building']
  },
  {
    id: STATISTIC_IDS.BRAND_CREDIBILITY_ADVANTAGE,
    percentage: 72,
    statement: 'of consumers find brands more credible than traditional media sources',
    source: 'Edelman Trust Barometer 2025',
    categories: ['brand-strategy', 'content-strategy']
  },
  {
    id: STATISTIC_IDS.AUDIO_BRANDING_RECALL_INCREASE,
    percentage: 96,
    statement: 'increase in brand recall when using audio branding elements',
    source: 'Audio Branding Academy Study',
    categories: ['visual-identity', 'brand-strategy']
  },
  {
    id: STATISTIC_IDS.SOUND_LOGO_RECOGNITION_SPEED,
    percentage: 800,
    statement: 'faster recognition speed for sound logos compared to visual logos',
    source: 'Audio Branding Academy Study',
    categories: ['visual-identity', 'digital-experience']
  },
  {
    id: STATISTIC_IDS.SONIC_BRANDING_PURCHASE_INTENT,
    percentage: 30,
    statement: 'increase in purchase intent when brands use consistent sonic branding',
    source: 'Audio Branding Academy Study',
    categories: ['brand-strategy', 'digital-experience']
  }
];

// Helper functions to filter statistics by categories
export const getStatisticsByCategory = (category: string): BrandingStatistic[] => {
  return brandingStatistics.filter(stat => stat.categories.includes(category));
};

export const getStatisticsByCategories = (categories: string[]): BrandingStatistic[] => {
  return brandingStatistics.filter(stat => 
    categories.some(category => stat.categories.includes(category))
  );
};

export const getRandomStatistics = (count: number): BrandingStatistic[] => {
  const shuffled = [...brandingStatistics].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

export const getStatisticById = (id: string): BrandingStatistic | undefined => {
  return brandingStatistics.find(stat => stat.id === id);
};